name: CMake

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        
    - uses: actions/cache@v3
      id: positioning_signal_cache
      with:
        path: ${{github.workspace}}/data/GPSdata-DiscreteComponents-fs38_192-if9_55.bin
        key: ${{ runner.os }}-positioning_signal_cache
        
    - uses: actions/cache@v3
      id: positioning_signal_ntlab_cache_fix
      with:
        path: ${{github.workspace}}/data/ntlab.bin
        key: ${{ runner.os }}-positioning_signal_ntlab_cache_fix

    - name: Install IPP
      run: wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18487/l_BaseKit_p_2022.1.2.146.sh && mkdir ONEAPI_ROOT && sudo sh ./l_BaseKit_p_2022.1.2.146.sh -a --components intel.oneapi.lin.ipp.devel -s --eula accept --install-dir ONEAPI_ROOT && export ONEAPI_ROOT=${PWD}/ONEAPI_ROOT
      
    - uses: actions/cache@v3
      id: vcpkg-cache
      with:
        path: vcpkg
        key: ${{ runner.os }}-vcpkg

    - name: Get vcpkg
      if: steps.vcpkg-cache.outputs.cache-hit != 'true'
      run: git clone https://github.com/microsoft/vcpkg.git --depth 1

    - name: Bootstrap vcpkg
      if: steps.vcpkg-cache.outputs.cache-hit != 'true'
      run: ./vcpkg/bootstrap-vcpkg.sh

    - name: Install dependencies
      if: steps.vcpkg-cache.outputs.cache-hit != 'true'
      run: ./vcpkg/vcpkg install boost-iostreams boost-timer boost-system boost-circular-buffer gtest benchmark fftw3[threads]

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=/home/runner/work/ugsdr/ugsdr/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} -V
